services:
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      - POSTGRES_USER=stock_user
      - POSTGRES_PASSWORD=stock_pass
      - POSTGRES_DB=stock_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app/backend
    environment:
      - SECRET_KEY=stock_secret_key_12345
      - DATABASE_URL=postgresql://stock_user:stock_pass@db:5432/stock_db
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  pgdata: